"""BZN dependency scanning: stock ODF list and ASCII/binary BZN parser.

Extracted unchanged from the BZN Toolbox ``bzn_scan`` module.
"""
import os
import re
import struct

# To update this, run the script I gave you previously and paste the result here
STOCK_ODF_LIST = [
    "abbar7.odf",
    "abbarr.odf",
    "abcafe.odf",
    "abcomm.odf",
    "abhang.odf",
    "abhqc3.odf",
    "abhqcp.odf",
    "ablpad.odf",
    "ablpow.odf",
    "abmbld.odf",
    "abshld.odf",
    "absilo.odf",
    "absiloa.odf",
    "abspow.odf",
    "abspowa.odf",
    "abstor.odf",
    "abstora.odf",
    "absupp.odf",
    "abtowe.odf",
    "abtowe02.odf",
    "abtowe03.odf",
    "abtowe2.odf",
    "abwpow.odf",
    "abwpowa.odf",
    "ammomina.odf",
    "ammomine.odf",
    "anchor.odf",
    "apammo.odf",
    "apammoa.odf",
    "apammob.odf",
    "apartl.odf",
    "apbase.odf",
    "apblst.odf",
    "apblstb.odf",
    "apblstg.odf",
    "apbltm.odf",
    "apbltmg.odf",
    "apbltmr.odf",
    "apbolt.odf",
    "apboltg.odf",
    "apboltr.odf",
    "apbsstb.odf",
    "apcamr.odf",
    "apcmet.odf",
    "apdrop.odf",
    "apflar.odf",
    "apflsh.odf",
    "apflshb.odf",
    "apflshg.odf",
    "apgmini.odf",
    "aphartl.odf",
    "aphorn.odf",
    "apmagg.odf",
    "apmasg.odf",
    "apmcur.odf",
    "apmdmg.odf",
    "apmini.odf",
    "apmits.odf",
    "apmort.odf",
    "apphan.odf",
    "appopg.odf",
    "approx.odf",
    "apredf.odf",
    "aprepa.odf",
    "aprepaa.odf",
    "aprepab.odf",
    "aprktb.odf",
    "apsand.odf",
    "apscrap.odf",
    "apshdw.odf",
    "apsite.odf",
    "apspln.odf",
    "apsplng.odf",
    "apsplnr.odf",
    "apsstb.odf",
    "apsstba.odf",
    "apstab.odf",
    "aptagg.odf",
    "aptech.odf",
    "apthmp.odf",
    "apwrck.odf",
    "apwrcka.odf",
    "apwrckb.odf",
    "aspilo.odf",
    "assold.odf",
    "asuser.odf",
    "asusera.odf",
    "audio.odf",
    "avapc.odf",
    "avarmp.odf",
    "avartl.odf",
    "avartla.odf",
    "avcns7.odf",
    "avcns8.odf",
    "avcns9.odf",
    "avcnst.odf",
    "avdemo.odf",
    "avfigh.odf",
    "avfimp.odf",
    "avhaul.odf",
    "avhraz.odf",
    "avhrmp.odf",
    "avlamp.odf",
    "avland.odf",
    "avltmp.odf",
    "avltnk.odf",
    "avmine.odf",
    "avmu7.odf",
    "avmu8.odf",
    "avmuf.odf",
    "avmuf4.odf",
    "avmuf5.odf",
    "avmuf6.odf",
    "avrckt.odf",
    "avrec2.odf",
    "avrec3.odf",
    "avrec4.odf",
    "avrec5.odf",
    "avrec6.odf",
    "avrec7.odf",
    "avrec8.odf",
    "avrecy.odf",
    "avremp.odf",
    "avret3.odf",
    "avret4.odf",
    "avsav.odf",
    "avscab.odf",
    "avscav.odf",
    "avsl7.odf",
    "avsl8.odf",
    "avslf.odf",
    "avslf5.odf",
    "avslf6.odf",
    "avtam2.odf",
    "avtamp.odf",
    "avtank.odf",
    "avtest.odf",
    "avtump.odf",
    "avturr.odf",
    "avwalk.odf",
    "avwamp.odf",
    "b_ambldg.odf",
    "b_amcmbt.odf",
    "b_amextr.odf",
    "b_ampers.odf",
    "b_amprod.odf",
    "b_amsign.odf",
    "b_bdbldg.odf",
    "b_bdcmbt.odf",
    "b_bdextr.odf",
    "b_bdpers.odf",
    "b_bdprod.odf",
    "b_bdsign.odf",
    "b_chbldg.odf",
    "b_chcmbt.odf",
    "b_chextr.odf",
    "b_chpers.odf",
    "b_chprod.odf",
    "b_chsign.odf",
    "b_hdbld1.odf",
    "b_hdbld2.odf",
    "b_hdbld3.odf",
    "b_mines.odf",
    "b_misn03.odf",
    "b_misn07.odf",
    "b_misn08.odf",
    "b_misn09.odf",
    "b_misn12.odf",
    "b_misn13.odf",
    "b_misn14.odf",
    "b_misns4.odf",
    "b_misns5.odf",
    "b_misns6.odf",
    "b_misns7.odf",
    "b_misns8.odf",
    "b_nebldg.odf",
    "b_olbld1.odf",
    "b_olbld2.odf",
    "b_sobldg.odf",
    "b_socmbt.odf",
    "b_soextr.odf",
    "b_sopers.odf",
    "b_soprod.odf",
    "b_sosign.odf",
    "b_wpcan2.odf",
    "b_wpcann.odf",
    "b_wpmort.odf",
    "b_wprock.odf",
    "b_wpspe2.odf",
    "b_wpspec.odf",
    "bbbarr.odf",
    "bbcafe.odf",
    "bbcom2.odf",
    "bbcomm.odf",
    "bbhang.odf",
    "bbhanga.odf",
    "bbhqcp.odf",
    "bblpad.odf",
    "bblpow.odf",
    "bbmbld.odf",
    "bbshld.odf",
    "bbsilo.odf",
    "bbspow.odf",
    "bbstor.odf",
    "bbsupp.odf",
    "bbtowe.odf",
    "bbwpow.odf",
    "blast.odf",
    "blastb.odf",
    "blastg.odf",
    "bolt.odf",
    "boltg.odf",
    "boltmine.odf",
    "boltming.odf",
    "boltminr.odf",
    "boltr.odf",
    "bouncebm.odf",
    "bsheav.odf",
    "bspilo.odf",
    "bssold.odf",
    "bsuser.odf",
    "build.odf",
    "build_a.odf",
    "build_b.odf",
    "build_c.odf",
    "build_h.odf",
    "build_o.odf",
    "build_pw.odf",
    "build_s.odf",
    "bullet1.odf",
    "bullet1a.odf",
    "bullet1b.odf",
    "bullet1g.odf",
    "bullet2.odf",
    "bullet5.odf",
    "bullet6.odf",
    "bullet6a.odf",
    "bv0001.odf",
    "bv0002.odf",
    "bvapc.odf",
    "bvapca.odf",
    "bvapcb.odf",
    "bvartl.odf",
    "bvcnst.odf",
    "bvfigh.odf",
    "bvfigha.odf",
    "bvhapc.odf",
    "bvhaul.odf",
    "bvhraz.odf",
    "bvhraza.odf",
    "bvltnk.odf",
    "bvltnka.odf",
    "bvmine.odf",
    "bvmru.odf",
    "bvmuf.odf",
    "bvmufa.odf",
    "bvmufb.odf",
    "bvra8.odf",
    "bvraz.odf",
    "bvrckt.odf",
    "bvrdev.odf",
    "bvrdeva.odf",
    "bvrec3.odf",
    "bvrec8.odf",
    "bvrecy.odf",
    "bvrecya.odf",
    "bvrecyb.odf",
    "bvrecyc.odf",
    "bvrecyd.odf",
    "bvrecye.odf",
    "bvremp.odf",
    "bvrmpa.odf",
    "bvrmpb.odf",
    "bvsca8.odf",
    "bvscav.odf",
    "bvslf.odf",
    "bvslfa.odf",
    "bvslfb.odf",
    "bvslfc.odf",
    "bvslfd.odf",
    "bvtank.odf",
    "bvtanka.odf",
    "bvtump.odf",
    "bvtur8.odf",
    "bvturr.odf",
    "bvwalk.odf",
    "cbbarr.odf",
    "cbcafe.odf",
    "cbcomm.odf",
    "cbhang.odf",
    "cbhanga.odf",
    "cbhqcp.odf",
    "cblasr.odf",
    "cblpad.odf",
    "cblpada.odf",
    "cblpow.odf",
    "cbmbld.odf",
    "cbmblda.odf",
    "cbport.odf",
    "cbshld.odf",
    "cbsilo.odf",
    "cbsiloa.odf",
    "cbspow.odf",
    "cbspowa.odf",
    "cbsupp.odf",
    "cbtowe.odf",
    "cbtowea.odf",
    "cbtoweb.odf",
    "cbtowec.odf",
    "cbtowed.odf",
    "cbtowee.odf",
    "cbtowef.odf",
    "cbwpow.odf",
    "cbwpowa.odf",
    "charge1.odf",
    "charge2.odf",
    "charge3.odf",
    "charge4.odf",
    "charge5.odf",
    "charge6.odf",
    "check.odf",
    "chunk.odf",
    "cnstblob.odf",
    "cpcamr.odf",
    "cpsstb.odf",
    "cpsstba.odf",
    "cspilo.odf",
    "cspiloa.odf",
    "cssold.odf",
    "cssolda.odf",
    "csuser.odf",
    "csusera.odf",
    "csuserb.odf",
    "cvapc.odf",
    "cvapca.odf",
    "cvapcb.odf",
    "cvapcc.odf",
    "cvartl.odf",
    "cvartla.odf",
    "cvcnst.odf",
    "cvfigh.odf",
    "cvfigha.odf",
    "cvfighb.odf",
    "cvfighc.odf",
    "cvfighd.odf",
    "cvfighe.odf",
    "cvfighf.odf",
    "cvfighg.odf",
    "cvfighh.odf",
    "cvfimp.odf",
    "cvhaul.odf",
    "cvhaula.odf",
    "cvhmpa.odf",
    "cvhmpb.odf",
    "cvhraz.odf",
    "cvhraza.odf",
    "cvhrazb.odf",
    "cvhtnk.odf",
    "cvhzmp.odf",
    "cvltnk.odf",
    "cvmine.odf",
    "cvminea.odf",
    "cvmuf.odf",
    "cvmufa.odf",
    "cvmufb.odf",
    "cvmufc.odf",
    "cvmump.odf",
    "cvraz.odf",
    "cvrckt.odf",
    "cvrecy.odf",
    "cvrecya.odf",
    "cvrecyd.odf",
    "cvrecye.odf",
    "cvremp.odf",
    "cvscav.odf",
    "cvscava.odf",
    "cvscavb.odf",
    "cvslf.odf",
    "cvslfa.odf",
    "cvslfb.odf",
    "cvtank.odf",
    "cvtmpa.odf",
    "cvtnk.odf",
    "cvtnka.odf",
    "cvtnkb.odf",
    "cvtnkc.odf",
    "cvtnkd.odf",
    "cvturr.odf",
    "cvturra.odf",
    "cvturrb.odf",
    "cvturrc.odf",
    "cvwalk.odf",
    "cvwamp.odf",
    "cvwo003.odf",
    "cvwo004.odf",
    "dayquake.odf",
    "dmgvhcl1.odf",
    "dmgvhcl2.odf",
    "dmgvhcl3.odf",
    "dmgvhcl4.odf",
    "dummy.odf",
    "dust.odf",
    "eggeizr1.odf",
    "engflame.odf",
    "engsplsh.odf",
    "fireball.odf",
    "flame.odf",
    "flare.odf",
    "flash.odf",
    "flashb.odf",
    "flashch.odf",
    "flashg.odf",
    "ga7stab.odf",
    "gammo.odf",
    "gammoa.odf",
    "gatstab.odf",
    "gatstaba.odf",
    "gblast.odf",
    "gblastb.odf",
    "gblastg.odf",
    "gbolt.odf",
    "gboltg.odf",
    "gboltmig.odf",
    "gboltmin.odf",
    "gboltmir.odf",
    "gboltr.odf",
    "gbspstab.odf",
    "gcomet.odf",
    "gdummy.odf",
    "gflare.odf",
    "gflashch.odf",
    "gflashgb.odf",
    "gflashgg.odf",
    "gflashgn.odf",
    "ghartila.odf",
    "ghartill.odf",
    "ghartmp.odf",
    "ghornet.odf",
    "ghrntai.odf",
    "gmaggun.odf",
    "gmasgren.odf",
    "gmbolt.odf",
    "gmboltg.odf",
    "gmboltr.odf",
    "gmcurmin.odf",
    "gmdmgun.odf",
    "gminigna.odf",
    "gminignb.odf",
    "gminignc.odf",
    "gminigrn.odf",
    "gminigun.odf",
    "gminisov.odf",
    "gmitsmin.odf",
    "gmortar.odf",
    "gnavdrop.odf",
    "gobject.odf",
    "gphantom.odf",
    "gpopgun.odf",
    "gproxmin.odf",
    "gquake.odf",
    "gredfld.odf",
    "grenade.odf",
    "grepa.odf",
    "grepaa.odf",
    "grktbomb.odf",
    "gsandbag.odf",
    "gshadow.odf",
    "gsitecam.odf",
    "gsnipe.odf",
    "gsplint.odf",
    "gsplinta.odf",
    "gsplintg.odf",
    "gsplintr.odf",
    "gspstab.odf",
    "gspstaba.odf",
    "gspstabb.odf",
    "gspstabc.odf",
    "gspstabd.odf",
    "gtaggun.odf",
    "gtechno.odf",
    "gtminig.odf",
    "gtminis.odf",
    "gtminisa.odf",
    "gwasp.odf",
    "handgun.odf",
    "hbblda.odf",
    "hbbldb.odf",
    "hbbldc.odf",
    "hbbldd.odf",
    "hbblde.odf",
    "hbbldf.odf",
    "hbcerb.odf",
    "hbchar.odf",
    "hbcrys.odf",
    "hbdayw.odf",
    "hbelec.odf",
    "hbfact.odf",
    "hbfacta.odf",
    "hbflsh.odf",
    "hbhydr.odf",
    "hbmasg.odf",
    "hbpopg.odf",
    "hbptow.odf",
    "hbpvir.odf",
    "hbsbmi.odf",
    "hbspln.odf",
    "hbtran00.odf",
    "hbtrn200.odf",
    "heatmsl.odf",
    "hocrys.odf",
    "hvsat.odf",
    "hvsav.odf",
    "hvsrb.odf",
    "imagemsl.odf",
    "magpull.odf",
    "magpulla.odf",
    "magpush.odf",
    "mbolt.odf",
    "mboltg.odf",
    "mboltr.odf",
    "netveh.odf",
    "nparr.odf",
    "npscr1.odf",
    "npscr2.odf",
    "npscr3.odf",
    "nvghst.odf",
    "obcmmi.odf",
    "obcurt.odf",
    "obcycl.odf",
    "obdata.odf",
    "obdataa.odf",
    "obhavc.odf",
    "obheph.odf",
    "obher100.odf",
    "obher200.odf",
    "obher300.odf",
    "oblema.odf",
    "oblemb.odf",
    "oblemc.odf",
    "oblemd.odf",
    "obmagc.odf",
    "obmits.odf",
    "obrfld.odf",
    "obstp1.odf",
    "obstp2.odf",
    "obstp3.odf",
    "obstp4.odf",
    "obstp5.odf",
    "obstp6.odf",
    "obstp7.odf",
    "obstp8.odf",
    "obtags.odf",
    "particle.odf",
    "plasma.odf",
    "player.odf",
    "playrt.odf",
    "playsv.odf",
    "popper.odf",
    "poproc.odf",
    "portblob.odf",
    "prodsmok.odf",
    "proxmina.odf",
    "proxminb.odf",
    "proxminc.odf",
    "proxmind.odf",
    "proxmine.odf",
    "proxminf.odf",
    "pspwn_1.odf",
    "radarmsl.odf",
    "repamina.odf",
    "repamine.odf",
    "rocket.odf",
    "rocket2.odf",
    "rocket3.odf",
    "rocket3a.odf",
    "rocket3b.odf",
    "rocket3c.odf",
    "rocket3d.odf",
    "rocketa.odf",
    "rocketb3.odf",
    "savmf.odf",
    "savs8.odf",
    "savtnk.odf",
    "sb0002.odf",
    "sbbarr.odf",
    "sbbarra.odf",
    "sbcafe.odf",
    "sbcom7.odf",
    "sbcomm.odf",
    "sbhang.odf",
    "sbhanga.odf",
    "sbhqcp.odf",
    "sbhqt1.odf",
    "sbhqt2.odf",
    "sblpad.odf",
    "sblpd2.odf",
    "sblpow.odf",
    "sblpowa.odf",
    "sblpowb.odf",
    "sbmbld.odf",
    "sbmblda.odf",
    "sbmbldb.odf",
    "sbshld.odf",
    "sbsilo.odf",
    "sbsiloa.odf",
    "sbspow.odf",
    "sbspowa.odf",
    "sbsupp.odf",
    "sbtowe.odf",
    "sbtowea.odf",
    "sbtoweb.odf",
    "sbtowec.odf",
    "sbtowed.odf",
    "sbtowee.odf",
    "sbwpow.odf",
    "sbwpowa.odf",
    "seismic.odf",
    "sfield.odf",
    "shell.odf",
    "shella.odf",
    "smoke.odf",
    "snipe.odf",
    "spammo.odf",
    "spartl.odf",
    "spblst.odf",
    "spbolt.odf",
    "spcamr.odf",
    "spcmet.odf",
    "spflar.odf",
    "spflsh.odf",
    "sphorn.odf",
    "splintb2.odf",
    "splintbg.odf",
    "splintbm.odf",
    "splintbr.odf",
    "splinter.odf",
    "splintg2.odf",
    "splintr2.odf",
    "splintrg.odf",
    "splintrr.odf",
    "splntbma.odf",
    "spmagg.odf",
    "spmasg.odf",
    "spmcur.odf",
    "spmdmg.odf",
    "spmini.odf",
    "spmits.odf",
    "spmort.odf",
    "spphan.odf",
    "sppopg.odf",
    "spprox.odf",
    "spredf.odf",
    "sprepa.odf",
    "sprktb.odf",
    "spsand.odf",
    "spshdw.odf",
    "spsite.odf",
    "spspln.odf",
    "spsstb.odf",
    "spstab.odf",
    "sptagg.odf",
    "sptech.odf",
    "spthmp.odf",
    "sscr_1.odf",
    "sspilo.odf",
    "sssold.odf",
    "ssuser.odf",
    "ssusera.odf",
    "ssuserb.odf",
    "ssuserc.odf",
    "svap2.odf",
    "svap7.odf",
    "svapc.odf",
    "svapc13.odf",
    "svapca.odf",
    "svapcb.odf",
    "svapcc.odf",
    "svapcd.odf",
    "svapce.odf",
    "svapcf.odf",
    "svapcg.odf",
    "svapch.odf",
    "svapci.odf",
    "svapcj.odf",
    "svapck.odf",
    "svapcl.odf",
    "svapcm.odf",
    "svapcn.odf",
    "svapco.odf",
    "svapcp.odf",
    "svapcq.odf",
    "svapcr.odf",
    "svapcs.odf",
    "svarmp.odf",
    "svartl.odf",
    "svartla.odf",
    "svcnst.odf",
    "svdemo.odf",
    "svfi12.odf",
    "svfigh.odf",
    "svfigha.odf",
    "svfimp.odf",
    "svhaul.odf",
    "svhaula.odf",
    "svhaulb.odf",
    "svhr13.odf",
    "svhraz.odf",
    "svhrmp.odf",
    "svlt13.odf",
    "svltnk.odf",
    "svltnka.odf",
    "svmfs8.odf",
    "svmine.odf",
    "svmuf.odf",
    "svmuf13.odf",
    "svrckt.odf",
    "svrecy.odf",
    "svremp.odf",
    "svsav.odf",
    "svscav.odf",
    "svscava.odf",
    "svslf.odf",
    "svtamp.odf",
    "svtank.odf",
    "svtanka.odf",
    "svtas8.odf",
    "svtk13.odf",
    "svtnk7.odf",
    "svtump.odf",
    "svturr.odf",
    "svturra.odf",
    "svturrb.odf",
    "svturrc.odf",
    "svwalk.odf",
    "svwalka.odf",
    "svwamp.odf",
    "svwatm.odf",
    "swarmer.odf",
    "switch.odf",
    "tracer.odf",
    "ubtart.odf",
    "waspmsl.odf",
    "xbldxpl.odf",
    "xbldxpla.odf",
    "xbmbxpl.odf",
    "xbulbld.odf",
    "xbulcar.odf",
    "xbulgnd.odf",
    "xcarxpl.odf",
    "xcarxpla.odf",
    "xcarxplb.odf",
    "xgasgnd.odf",
    "xgasxpl.odf",
    "xgndshk.odf",
    "xlasbld.odf",
    "xlascar.odf",
    "xlascar2.odf",
    "xlasgnd.odf",
    "xlgtbld.odf",
    "xlgtbldg.odf",
    "xlgtbldr.odf",
    "xlgtcar.odf",
    "xlgtcarg.odf",
    "xlgtcarr.odf",
    "xlgtgnd.odf",
    "xlgtgndg.odf",
    "xlgtgndr.odf",
    "xminxpl.odf",
    "xmslbld.odf",
    "xmslcar.odf",
    "xmslgnd.odf",
    "xpltrsa.odf",
    "xpltrsb.odf",
    "xpltrsc.odf",
    "xpltrsd.odf",
    "xpltrse.odf",
    "xpltrsf.odf",
    "xpltrsg.odf",
    "xpltrsh.odf",
    "xpltrsi.odf",
    "xpltrsj.odf",
    "xpltrsk.odf",
    "xpltrsl.odf",
    "xpltrsm.odf",
    "xpltrsn.odf",
    "xpltrso.odf",
    "xpltrsp.odf",
    "xpltrsq.odf",
    "xpltrsr.odf",
    "xpltrss.odf",
    "xpopfir.odf",
    "xsecxpl.odf",
    "xsecxpla.odf",
    "xtorxpl.odf",
    "xtorxpla.odf",
    "xtorxplb.odf"
]
STOCK_SET = {name.lower() for name in STOCK_ODF_LIST}


class BinaryFieldType:
    DATA_VOID = 0
    DATA_BOOL = 1
    DATA_CHAR = 2
    DATA_SHORT = 3
    DATA_LONG = 4
    DATA_FLOAT = 5
    DATA_DOUBLE = 6
    DATA_ID = 7
    DATA_PTR = 8
    DATA_VEC3D = 9
    DATA_VEC2D = 10
    DATA_MAT3DOLD = 11
    DATA_MAT3D = 12
    DATA_STRING = 13
    DATA_QUAT = 14

class BZNParser:
    def __init__(self, filepath):
        self.filepath = filepath
        self.odf_matches = set()

    def parse(self):
        try:
            with open(self.filepath, 'rb') as f:
                data = f.read()

            # Always run ASCII extraction on the whole file first as it catches ODFs in both formats
            content_text = data.decode('ascii', errors='ignore')
            self._parse_ascii(content_text)
            
            # Detect if it's binary and find where binary starts
            # Look for binarySave flag in the header
            binary_save_match = re.search(r"binarySave\s*\[\d+\]\s*=\s*(true|1)", content_text)
            if binary_save_match:
                # Binary data starts after the binarySave line value
                # Usually there's a msn_filename and other fields as binary tokens
                # We'll start scanning from the end of the binarySave match
                binary_start_pos = binary_save_match.end()
                # Skip any whitespace/newlines after the "true"
                while binary_start_pos < len(data) and data[binary_start_pos] in b' \t\r\n':
                    binary_start_pos += 1
                
                self._parse_binary(data, binary_start_pos)

            return self.odf_matches
        except Exception as e:
            print(f"Error parsing {self.filepath}: {e}")
            return set()

    def _parse_ascii(self, content):
        # These fields can carry object/ODF identifiers. Keep whitespace
        # matching horizontal: \s* would also consume newlines, so an empty
        # field such as "buildClass [1] =" could steal the next field name
        # (for example "buildDoneTime") and report it as a fake dependency.
        tags = [r"PrjID", r"buildClass", r"dropClass", r"curPilot", r"label"]
        for tag in tags:
            pattern = (
                fr"{tag}[ \t]*\[\d+\][ \t]*=[ \t]*"
                fr"(?:\"([^\"\r\n]+)\"|([\w-]+)(?![\w-]))"
            )
            matches = re.finditer(pattern, content)
            for match in matches:
                m = match.group(1) or match.group(2)
                if m and not m.isdigit():
                    self.odf_matches.add(m)

        # BZ1 legacy format matches. Apply the same same-line rule here so an
        # empty PrjID cannot consume the following line either.
        matches = re.finditer(
            r"PrjID[ \t]*=[ \t]*(?:\"([^\"\r\n]+)\"|([\w-]+)(?![\w-]))",
            content,
        )
        for match in matches:
            m = match.group(1) or match.group(2)
            if m and not m.isdigit():
                self.odf_matches.add(m)

    def _parse_binary(self, data, start_pos):
        # Sequential binary parsing is much more reliable than scanning
        pos = start_pos
        while pos + 4 <= len(data):
            try:
                # Type code (2 bytes, usually only first byte is used)
                type_code = data[pos]
                # Size (2 bytes)
                size_bytes = data[pos+2:pos+4]
                size = struct.unpack("<H", size_bytes)[0]
                
                chunk_start = pos + 4
                if chunk_start + size > len(data):
                    break # End of data or malformed
                
                # Only trust DATA_ID (7) for ODF names. DATA_CHAR (2) are labels.
                if type_code == BinaryFieldType.DATA_ID:
                    value_bytes = data[chunk_start:chunk_start+size]
                    value = value_bytes.decode('ascii', errors='ignore').strip('\x00')
                    # Sanity check for ODF names
                    if re.match(r"^[a-zA-Z0-9_-]+$", value) and not value.isdigit():
                        if 3 <= len(value) <= 64:
                            self.odf_matches.add(value)
                elif type_code == BinaryFieldType.DATA_CHAR:
                    # Labels can sometimes contain ODF names if the user named them that way,
                    # but it's safer to skip them to avoid false positives.
                    # For now, we'll exclude them unless we find a reason to include.
                    pass
                
                # Move to the next token
                pos = chunk_start + size
            except:
                # If sequential parsing fails, we might be desynced.
                # In a robust parser we'd handle this, but for dependency scanning
                # we can just stop or try to resync.
                break
