"""Read any uncompressed DDS and rewrite it as DXT1/DXT5, mip chain intact.

This is the DDS path for tex_man.py, replacing a texconv.exe subprocess.

* texconv is an external binary that had to be downloaded and placed next to the
  exe -- it was step 3 of the README's setup. This is pure Python on the
  numpy/Pillow dependencies already declared, so that step is gone, along with
  the temporary TGA and the subprocess per image.
* **Pillow reads mip 0 and nothing else.** A DDS has no `n_frames` and `seek(1)`
  raises EOFError, so the author's mip chain is invisible through it; `read_dds`
  returns every level, and they are transcoded in place rather than resampled.
  On a 2048-square diffuse map that is 12 authored levels kept instead of 12
  regenerated by a filter nobody chose.
* **Pillow's DDS writer cannot block-compress or write mips**: it emits an
  uncompressed surface with the FourCC zeroed and mipCount 0. So the write half
  has to exist here regardless.
* Channel order comes from the pixel-format bit masks rather than being assumed,
  which keeps the reader correct on the ABGR files (nine in ISDF Chronicles,
  against 418 ARGB) without special-casing.

Measured against Pillow 12.3.0 on 2026-09-15, across all six uncompressed pixel
layouts present in ISDF Chronicles (32bpp ARGB and ABGR, 24bpp, R5G6B5, A1R5G5B5,
8bpp luminance), the two readers agree exactly on mip 0 everywhere except R5G6B5,
where they differ by at most 1/255 from a different bit-expansion rounding.
Earlier revisions of this file claimed Pillow could not open R5G6B5 at all; that
is no longer true and the mip chain is the reason the reader stays.

The colour encoder is `bc1.py`, shared with Battlezone98Redux_WorldBuilder: a
PCA endpoint fit plus a least-squares re-solve, which measures better than
Pillow's bounding-box encoder on every sample tried (about 5 dB on a
tangent-space normal map). Its `_fit` always emits c0 > c1, the opaque
four-colour block, so the same blocks are valid as the colour half of DXT5.
"""
import os
import struct

import numpy as np

try:
    from . import bc1
except ImportError:                       # running as a plain script
    from bztoolbox.modules.textures import bc1

DDPF_ALPHAPIXELS = 0x1
DDPF_FOURCC = 0x4
DDPF_RGB = 0x40
DDPF_LUMINANCE = 0x20000

DDSD_MIPMAPCOUNT = 0x20000
DDSD_BASE = 0x1 | 0x2 | 0x4 | 0x1000 | 0x80000        # CAPS HEIGHT WIDTH PF LINEARSIZE
DDSD_BASE_PITCH = 0x1 | 0x2 | 0x4 | 0x1000 | 0x8      # ...but uncompressed says PITCH
DDSCAPS = 0x1000 | 0x8 | 0x400000                     # TEXTURE COMPLEX MIPMAP


class Unsupported(Exception):
    pass


def _mask_decode(values, mask):
    """Scale an arbitrary-width bit field up to a full 0..255 channel."""
    if mask == 0:
        return None
    shift = (mask & -mask).bit_length() - 1
    span = mask >> shift
    raw = (values & mask) >> shift
    if span == 255:
        return raw.astype(np.uint8)
    # widen so the field maximum maps exactly onto 255, e.g. 31 -> 255
    return ((raw.astype(np.uint32) * 255 + span // 2) // span).astype(np.uint8)


def read_dds(path):
    """-> (levels, info). levels is a list of HxWx4 uint8 RGBA arrays, mip 0 first."""
    with open(path, "rb") as fh:
        blob = fh.read()
    if blob[:4] != b"DDS " or len(blob) < 128:
        raise Unsupported("not a DDS")
    flags, height, width = struct.unpack("<3I", blob[8:20])
    mipcount = struct.unpack("<I", blob[28:32])[0]
    pfflags, fourcc, bits = struct.unpack("<I4sI", blob[80:92])
    rm, gm, bm, am = struct.unpack("<4I", blob[92:108])
    caps2 = struct.unpack("<I", blob[112:116])[0]
    if pfflags & DDPF_FOURCC:
        raise Unsupported("already compressed (%s)"
                          % fourcc.decode("ascii", "replace").strip())
    if caps2 & 0x200:
        raise Unsupported("cubemap container")
    if bits not in (8, 16, 24, 32):
        raise Unsupported("%d bits per pixel" % bits)
    levels_n = mipcount if (flags & DDSD_MIPMAPCOUNT) and mipcount else 1

    bpp = bits // 8
    dt = {1: np.uint8, 2: "<u2", 4: "<u4"}.get(bpp)
    off, out = 128, []
    for i in range(levels_n):
        w, h = max(1, width >> i), max(1, height >> i)
        n = w * h * bpp
        if off + n > len(blob):
            break                          # truncated chain: keep what is there
        chunk = blob[off:off + n]
        off += n
        if bpp == 3:
            v = np.frombuffer(chunk, np.uint8).reshape(h, w, 3).astype(np.uint32)
            vals = v[:, :, 0] | (v[:, :, 1] << 8) | (v[:, :, 2] << 16)
        else:
            vals = np.frombuffer(chunk, dt).reshape(h, w).astype(np.uint32)

        rgba = np.empty((h, w, 4), np.uint8)
        if pfflags & DDPF_LUMINANCE:
            lum = _mask_decode(vals, rm if rm else 0xFF)
            rgba[:, :, 0] = rgba[:, :, 1] = rgba[:, :, 2] = lum
        elif pfflags & DDPF_RGB:
            for c, mask in enumerate((rm, gm, bm)):
                ch = _mask_decode(vals, mask)
                rgba[:, :, c] = 0 if ch is None else ch
        else:
            raise Unsupported("pixel format flags 0x%x" % pfflags)
        a = _mask_decode(vals, am) if (pfflags & DDPF_ALPHAPIXELS) else None
        rgba[:, :, 3] = 255 if a is None else a
        out.append(rgba)

    if not out:
        raise Unsupported("no readable mip data")
    info = dict(width=width, height=height, levels=len(out), bits=bits,
                pfflags=pfflags, size=len(blob))
    return out, info


# --- BC4 alpha blocks, the alpha half of DXT5 ---------------------------------

def _alpha_palette(a0, a1):
    """The eight decoded alpha values for an (a0, a1) pair, a0 > a1 mode."""
    a0f, a1f = a0.astype(np.float32), a1.astype(np.float32)
    steps = [a0f, a1f] + [((7 - k) * a0f + k * a1f) / 7.0 for k in range(1, 7)]
    return np.stack(steps, axis=1)                                   # (N,8)


def encode_bc4(alpha):
    """alpha: HxW uint8, both dims multiples of 4. -> packed 8-byte BC4 blocks."""
    h, w = alpha.shape
    bh, bw = h // 4, w // 4
    blocks = (alpha.reshape(bh, 4, bw, 4).transpose(0, 2, 1, 3)
                   .reshape(bh * bw, 16).astype(np.int32))
    hi, lo = blocks.max(1), blocks.min(1)
    flat = hi == lo

    # a0 > a1 selects the eight-value interpolated mode. A flat block cannot use
    # it (a0 == a1 falls into the six-value mode), but index 0 is still a0 there,
    # so the exact value survives -- hence the all-zero indices below.
    pal = _alpha_palette(hi, lo)                                     # (N,8)
    d = np.abs(blocks[:, :, None] - pal[:, None, :])                 # (N,16,8)
    idx = d.argmin(2).astype(np.uint64)
    idx = np.where(flat[:, None], np.uint64(0), idx)

    packed = (idx << (3 * np.arange(16, dtype=np.uint64))[None, :]).sum(1)
    out = np.empty((blocks.shape[0], 8), np.uint8)
    out[:, 0] = hi.astype(np.uint8)
    out[:, 1] = lo.astype(np.uint8)
    for k in range(6):
        out[:, 2 + k] = (packed >> np.uint64(8 * k)) & np.uint64(0xFF)
    return out.tobytes()


def decode_bc4(data, w, h):
    """Round-trip helper for the self-test and the verification pass."""
    b = np.frombuffer(data, np.uint8).reshape(-1, 8)
    a0, a1 = b[:, 0].astype(np.int32), b[:, 1].astype(np.int32)
    pal = _alpha_palette(a0, a1)
    six = a0 <= a1
    if six.any():                       # degenerate mode: 4 lerps, then 0 and 255
        a0f, a1f = a0.astype(np.float32), a1.astype(np.float32)
        alt = np.stack([a0f, a1f]
                       + [((5 - k) * a0f + k * a1f) / 5.0 for k in range(1, 5)]
                       + [np.zeros_like(a0f), np.full_like(a0f, 255.0)], axis=1)
        pal = np.where(six[:, None], alt, pal)
    bits = np.zeros(b.shape[0], np.uint64)
    for k in range(6):
        bits |= b[:, 2 + k].astype(np.uint64) << np.uint64(8 * k)
    idx = (bits[:, None] >> (3 * np.arange(16, dtype=np.uint64))[None, :]) & np.uint64(7)
    px = np.take_along_axis(pal, idx.astype(np.intp), 1)
    bh, bw = h // 4, w // 4
    return (px.reshape(bh, bw, 4, 4).transpose(0, 2, 1, 3)
              .reshape(h, w).astype(np.uint8))


# --- block-compressing a whole mip chain --------------------------------------

def _pad4(a):
    """Grow to a multiple of 4 by replicating the edge, for the sub-4px mips."""
    h, w = a.shape[:2]
    ph, pw = (-h) % 4, (-w) % 4
    if not ph and not pw:
        return a
    return np.pad(a, ((0, ph), (0, pw)) + ((0, 0),) * (a.ndim - 2), mode="edge")


def encode_level(rgba, fmt):
    a = _pad4(rgba)
    colour = bc1.encode_bc1(np.ascontiguousarray(a[:, :, :3]))
    if fmt == "DXT1":
        return colour
    alpha = encode_bc4(np.ascontiguousarray(a[:, :, 3]))
    c = np.frombuffer(colour, np.uint8).reshape(-1, 8)
    al = np.frombuffer(alpha, np.uint8).reshape(-1, 8)
    return np.concatenate([al, c], axis=1).tobytes()     # DXT5: alpha block first


def decode_level(data, w, h, fmt):
    """-> HxWx4 uint8 RGBA, for verifying what was actually written."""
    pw, ph = w + (-w) % 4, h + (-h) % 4
    if fmt == "DXT1":
        rgb = bc1.decode_bc1(data, pw, ph)
        a = np.full((ph, pw), 255, np.uint8)
    else:
        b = np.frombuffer(data, np.uint8).reshape(-1, 16)
        a = decode_bc4(b[:, :8].tobytes(), pw, ph)
        rgb = bc1.decode_bc1(b[:, 8:].tobytes(), pw, ph)
    return np.dstack([rgb, a])[:h, :w]


def write_dds(path, width, height, levels, fmt):
    """levels: list of encoded block payloads, mip 0 first."""
    bw, bh = max(1, (width + 3) // 4), max(1, (height + 3) // 4)
    linear = bw * bh * (8 if fmt == "DXT1" else 16)
    flags = DDSD_BASE | (DDSD_MIPMAPCOUNT if len(levels) > 1 else 0)
    h = struct.pack("<4s7I", b"DDS ", 124, flags, height, width, linear, 0, len(levels))
    h += b"\0" * 44                                        # dwReserved1[11]
    h += struct.pack("<II4s5I", 32, DDPF_FOURCC, fmt.encode(), 0, 0, 0, 0, 0)
    h += struct.pack("<5I", DDSCAPS if len(levels) > 1 else 0x1000, 0, 0, 0, 0)
    assert len(h) == 128, len(h)
    tmp = path + ".part"
    with open(tmp, "wb") as f:
        f.write(h)
        for lv in levels:
            f.write(lv)
    os.replace(tmp, path)


def write_dds_uncompressed(path, levels):
    """levels: list of HxWx4 uint8 RGBA arrays, mip 0 first. -> A8R8G8B8 DDS.

    The GUI's "Compression: None" option. Written here rather than left to
    Pillow because Pillow's DDS writer emits no mip chain, and because the whole
    point of this module is that one reader/writer pair round-trips: what
    `read_dds` gives back for an A8R8G8B8 file is exactly what this writes.

    Byte order on disk is B,G,R,A -- which is the same thing as the ARGB dword
    masks below on a little-endian machine, and what texconv's B8G8R8A8_UNORM
    used to produce here.
    """
    height, width = levels[0].shape[:2]
    flags = DDSD_BASE_PITCH | (DDSD_MIPMAPCOUNT if len(levels) > 1 else 0)
    h = struct.pack("<4s7I", b"DDS ", 124, flags, height, width,
                    width * 4, 0, len(levels))
    h += b"\0" * 44
    h += struct.pack("<II4s5I", 32, DDPF_RGB | DDPF_ALPHAPIXELS, b"\0\0\0\0", 32,
                     0x00FF0000, 0x0000FF00, 0x000000FF, 0xFF000000)
    h += struct.pack("<5I", DDSCAPS if len(levels) > 1 else 0x1000, 0, 0, 0, 0)
    assert len(h) == 128, len(h)
    tmp = path + ".part"
    with open(tmp, "wb") as f:
        f.write(h)
        for lv in levels:
            bgra = np.ascontiguousarray(lv[:, :, [2, 1, 0, 3]])
            f.write(bgra.tobytes())
    os.replace(tmp, path)


def build_chain(levels, width, height):
    """Source mips if the file shipped any, else a Lanczos chain down to 1x1.

    -> (levels, "kept" | "generated"). Transcoding the author's own chain is
    always preferred: it preserves whatever filter and hand-touching they used,
    and picking a resampler on their behalf is a decision this tool has no basis
    for making.
    """
    if len(levels) > 1:
        return levels, "kept"
    from PIL import Image
    im = Image.fromarray(levels[0], "RGBA")
    out, w, h = [levels[0]], width, height
    while w > 1 or h > 1:
        w, h = max(1, w // 2), max(1, h // 2)
        out.append(np.asarray(im.resize((w, h), Image.LANCZOS)))
    return out, "generated"


OPAQUE_FLOOR = 250


def has_real_alpha(levels, floor=OPAQUE_FLOOR):
    """True if mip 0 has alpha the renderer could act on.

    Mip 0 only: averaging in the smaller levels rounds a lone 254 back up to 255
    and reports a false opaque.

    The floor is not paranoia in the other direction either. ISDF Chronicles'
    mission loading screens are alpha 255 everywhere except 2432 texels at
    exactly 254, out of 8.4 million -- authoring noise from some round-trip, not
    intent. Taking `min < 255` literally there doubles the file (DXT5 over DXT1)
    to preserve one part in 255 of blend on 0.03% of an image that is drawn
    opaque and fullscreen. Anything still 98% opaque cannot be meaningfully
    see-through, and a channel carrying real packed data has a range that puts
    its minimum nowhere near this.
    """
    return bool(levels[0][:, :, 3].min() < floor)
