"""Regenerate battlezone/validation/data/bzrODFparams.txt from the loader schema.

The schema is ``research/odf_loader_schema.json`` in the BZ1_Source repository
(github.com/GrizzlyOne95/BZ1_Source): every ODF key the 1.5 and Redux class
loaders read, recovered from the decompiles and hash-verified. The params file
lists, per section, the keys Redux reads there; the mod scanner reports any
other key in a listed section as an unknown field.

Usage::

    python scripts/research/build_odf_params.py <BZ1_Source>/research/odf_loader_schema.json
"""

from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT = REPO_ROOT / "battlezone" / "validation" / "data" / "bzrODFparams.txt"

# XxxClass::Find reads classLabel from the family root section; it is not in
# the per-class key lists. Redux reads the explosion label from
# [ExplosionClass]; a bare [Explosion] root is only kept for dispatch.
ROOT_SECTIONS = ("GameObjectClass", "OrdnanceClass", "WeaponClass", "ExplosionClass", "Explosion")

# Keys whose absence breaks the object in Redux (odf_validator_rules.json).
REQUIRED = {("FlareMineClass", "payloadName")}

# Indexed key families: the schema records the first index (with or without a
# trailing "*"); the loader appends the index to the base name.
_INDEXED = re.compile(r"^(?P<base>.+?)(?P<first>0?1)\*?$")


def _family(key: dict) -> str | None:
    name = key["name"].rstrip("*")
    match = _INDEXED.match(key["name"])
    if not match:
        return None
    note = key.get("note", "")
    if key["name"].endswith("*") or ".." in note or "via" in note or "same scheme" in note \
            or "per-level" in note:
        return match.group("base")
    return None if name[-1] != "1" else match.group("base")


def build(schema: dict) -> str:
    sections: dict[str, dict[str, str]] = defaultdict(dict)
    skipped_15: dict[str, list[str]] = defaultdict(list)
    unresolved: list[str] = []
    for loader in schema["loaders"]:
        section = loader.get("section")
        if not section or not loader.get("keys"):
            continue
        for key in loader["keys"]:
            name = key["name"]
            if name.startswith("unknown_"):
                unresolved.append(f"{section} {key['key_hash']}")
                continue
            if not key.get("present_redux"):
                skipped_15[section].append(name)
                continue
            family = _family(key)
            token = f"{family}#" if family else name
            if (section, name) in REQUIRED:
                token = "!" + token
            info = key["type"] + ("" if key.get("present_15") else ", Redux only")
            sections[section].setdefault(token, info)
    for root in ROOT_SECTIONS:
        sections[root] = {"classLabel": "string, family root", **sections.get(root, {})}

    lines = [
        "// Keys the Battlezone 98 Redux class loaders read, per ODF section.",
        "// Generated by scripts/research/build_odf_params.py from BZ1_Source",
        f"// research/odf_loader_schema.json (schema_version {schema['schema_version']}); do not edit by hand.",
        "//",
        "// Section and key names are case-insensitive. A key under a section that",
        "// does not read it is dead in Redux (the engine uses the default).",
        "//   !key   the object breaks in Redux without it",
        "//   key#   indexed family: key1, key2, ... (targetReticle uses 01, 02, ...)",
        "// Sections not listed here are not checked key by key.",
    ]
    if skipped_15:
        lines.append("// Read by 1.5 only (dead in Redux): " + "; ".join(
            f"[{s}] {', '.join(k)}" for s, k in sorted(skipped_15.items())))
    if unresolved:
        lines.append("// Read by Redux under a name not yet recovered (hash only): " + "; ".join(unresolved))
    for section in sorted(sections, key=str.lower):
        lines.append("")
        lines.append(f"[{section}]")
        width = max(len(token) for token in sections[section])
        for token, info in sections[section].items():
            lines.append(f"{token.ljust(width)}  // {info}")
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("schema", type=Path)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args(argv)
    schema = json.loads(args.schema.read_text(encoding="utf-8"))
    args.output.write_text(build(schema), encoding="utf-8", newline="\n")
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
